### PR TITLE
Add simple console game the rock-paper-scissirs(roshambo)

### PR DESCRIPTION
**Pull request by Furmanchuk**

### CODE REVIEW

**Comment by alexposukhov** [comment]
Please add a detailed description to commit f63d826

**Comment by alexposukhov** [comment]
Please add while(true) {}  cycle to get more rounds in a raw.

**Comment by Furmanchuk** [comment]
> Please add a detailed description to commit [f63d826](https://github.com/Kernel-GL-HRK/gl_kernel_procamp_2021/commit/f63d826b7b87f5a724d388b3530f6cac99d3aab7)

Done.

**Comment by Furmanchuk** [comment]
> Please add while(true) {} cycle to get more rounds in a raw. Please make additional commit for this change

Done.

**Review by alexposukhov — APPROVED** [review]
Looks good to me

**Pull request merged**
